## Индивидуальное задание

### Дана целочисленная прямоугольная матрица.
#### Определить:
1) Количество столбцов, не содержащих ни одного нулевого элемента.<br>
2) Характеристикой строки целочисленной матрицы назовем сумму ее положительных четных элементов.<br>
3) Переставляя строки заданной матрицы, расположить их в соответствии с ростом характеристик.

In [277]:
import numpy as np

def inv_1(mx: str):
    mx = np.matrix(mx)
    
    mx_element_count_null = np.sum(mx == 0)
    mx_row_sum = np.sum(mx, axis=1)
    mx_row_sort_sum = np.sort(mx_row_sum, axis=0)
    mx_sort_sum = mx[np.argsort(mx_row_sum, axis=0).ravel(), :]
    return [mx_element_count_null, mx, mx_row_sum, mx_sort_sum, mx_row_sort_sum]

def input_mx():
    print("Введите матрица:")
    x = inv_1(input("  Введите элементы массива (пример: \'1 2; 3 4\'): mx ="))    
    print("\n Результат:\n")
    print("Элементы массива:\n", x[1])
    print("Элементы массива (сумма):\n", x[2])
    print("\n\nКоличество столбцов не содержащих ни одного 0 элемента:", x[0])
    print("\n\nУпорядоченная:")
    print("\nЭлементы массива:\n", x[3])
    print("\nЭлементы массива (сумма):\n", x[4])
    
#print( inv_1("10 11 0 13 14; 5 6 0 8 9; 10 0 12 10 4; 10 21 12 43 14; 1 2 3 4 0") )

input_mx()

Введите матрица:
  Введите элементы массива (пример: '1 2; 3 4'): mx =10 11 0 13 14; 5 6 0 8 9; 10 0 12 10 4; 10 21 12 43 14; 1 2 3 4 0

 Результат:

Элементы массива:
 [[10 11  0 13 14]
 [ 5  6  0  8  9]
 [10  0 12 10  4]
 [10 21 12 43 14]
 [ 1  2  3  4  0]]
Элементы массива (сумма):
 [[ 48]
 [ 28]
 [ 36]
 [100]
 [ 10]]


Количество столбцов не содержащих ни одного 0 элемента: 4


Упорядоченная:

Элементы массива:
 [[[ 1  2  3  4  0]
  [ 5  6  0  8  9]
  [10  0 12 10  4]
  [10 11  0 13 14]
  [10 21 12 43 14]]]

Элементы массива (сумма):
 [[ 10]
 [ 28]
 [ 36]
 [ 48]
 [100]]
